### PR TITLE
Add Tally integration

### PR DESCRIPTION
**Pull request by 0xzoz**
Add support for [Tally](https://tally.cash/) wallet. Tally is an open-source browser extension similar to Metamask.

### CODE REVIEW

**Review by 0xdef1cafe — CHANGES_REQUESTED** [review]
can you please bump `bnc-onboard` to `1.37.2` and commit the `yarn.lock` file too and we'll gladly get this merged!

**Comment by 0xdef1cafe** [comment]
and sorry for the delay getting back to you here, foxfarm is pretty stable and this one totally got overlooked 😔

**Comment by 0xzoz** [comment]
Thanks for the feedback @0xdef1cafe. The changes have been made.

**Review by theoboldfrazier — APPROVED** [review]

**Review by cjthompson — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xzoz** [comment]
@0xdef1cafe @andrewpjames13 @cjthompson we are doing a co-marketing push for the Tally wallet release on the 11/04/2022. This would allow users of your app to claim an airdrop. Who is the best person to reach out to for this? I can be contacted on discord at zoz.eth#6952

**Pull request merged**
